[package]
name = "hello"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_runtime = "0.4.0"
log = "0.4.14"
simple_logger = "1.11.0"
tokio = "1.13.1"
aws_lambda_events = "0.4.0"
http = "0.2.4"
